plugins {
    id 'scala'
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.scala-lang', name: 'scala-library', version: '2.13.15'
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}


kotlin {
    jvmToolchain(11)
}

