gatling.enterprise.package {
//  id = "18b7439addd3e171-4cbc-4322-87f6-5df9289bd01c"
  name = "private package11"
  team = "38efcc17-4880-4316-9794-691717b248d2"
  simulations = [
    {
      name = "Poc with docker control plane and  AWS private location"
      simulation = "com.adobe.gatlingpoc.PocSimulationDockerAws"
    },
  ]
}
