gatling.enterprise.package {
//  id = "16fd73ec-42ee-4236-b166-931371d7d0f6"
//  id = "91a8740c-7d47-4b38-93ac-e19eef918063"
  name = "private package8"
  team = "38efcc17-4880-4316-9794-691717b248d2"
  simulations = [
    {
      name = "Poc with K8s control plane and  K8s private location"
      simulation = "com.adobe.gatlingpoc.PocSimulationK8sK8s"
    },
  ]
}
