plugins {
    id 'scala'
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
    id("io.gatling.gradle") version "3.13.1.2"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.scala-lang', name: 'scala-library', version: '2.13.15'
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}


kotlin {
    jvmToolchain(11)
}

gatling {
    gatlingVersion = '3.13.1'
    enterprise {
//        apiToken = <apiToken from https://cloud.gatling.io/o/adobe-identity-poc/api-tokens>
        controlPlaneUrl "http://localhost:58080/"
//        packageId  "3d282047-d177-4098-866f-c5172bc35019"
    }
}

tasks {
    gatlingEnterpriseDeploy.group 'Gatling Enterprise'
    gatlingEnterprisePackage.group 'Gatling Enterprise'
    gatlingEnterpriseStart.group 'Gatling Enterprise'
    gatlingEnterpriseUpload.group 'Gatling Enterprise'
}
