apiVersion: v1
kind: PersistentVolume
metadata:
  name: gatling-cp-pv-volume
  labels:
    zuzu: "buburuzu"
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/gatling-cp-pv-volume  # Path on the host node
